export const userBookFavoriteConstants = {
	Create: {
		REQUEST : "USER_BOOK_FAVORITE_CREATE_REQUEST",
		SUCCESS : "USER_BOOK_FAVORITE_CREATE_SUCCESS",
		FAILURE : "USER_BOOK_FAVORITE_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "USER_BOOK_FAVORITE_GETPAGED_REQUEST",
		SUCCESS : "USER_BOOK_FAVORITE_GETPAGED_SUCCESS",
		FAILURE : "USER_BOOK_FAVORITE_GETPAGED_FAILURE"
	},
	Delete: {
		REQUEST : "USER_BOOK_FAVORITE_DELETE_REQUEST",
		SUCCESS : "USER_BOOK_FAVORITE_DELETE_SUCCESS",
		FAILURE : "USER_BOOK_FAVORITE_DELETE_FAILURE"
	},
	Clear: "USER_BOOK_FAVORITE_CLEAR"
}
