export const genreConstants = {
	Create: {
		REQUEST : "GENRE_CREATE_REQUEST",
		SUCCESS : "GENRE_CREATE_SUCCESS",
		FAILURE : "GENRE_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "GENRE_GETPAGED_REQUEST",
		SUCCESS : "GENRE_GETPAGED_SUCCESS",
		FAILURE : "GENRE_GETPAGED_FAILURE"
	},
	Update: {
		REQUEST : "GENRE_UPDATE_REQUEST",
		SUCCESS : "GENRE_UPDATE_SUCCESS",
		FAILURE : "GENRE_UPDATE_FAILURE"

	},
	Delete: {
		REQUEST : "GENRE_DELETE_REQUEST",
		SUCCESS : "GENRE_DELETE_SUCCESS",
		FAILURE : "GENRE_DELETE_FAILURE"
	},
	Restore: {
		REQUEST : "GENRE_RESTORE_REQUEST",
		SUCCESS : "GENRE_RESTORE_SUCCESS",
		FAILURE : "GENRE_RESTORE_FAILURE"
	},

	Clear: "GENRE_CLEAR"
}
