export const genreConstants = {
	Create: {
		REQUEST : "GENRE_CREATE_REQUEST",
		SUCCESS : "GENRE_CREATE_SUCCESS",
		FAILURE : "GENRE_CREATE_FAILURE"
	},
	GetPages: {
		REQUEST : "GENRE_GETPAGES_REQUEST",
		SUCCESS : "GENRE_GETPAGES_SUCCESS",
		FAILURE : "GENRE_GETPAGES_FAILURE"
	},
	Update: {
		REQUEST : "GENRE_UPDATE_REQUEST",
		SUCCESS : "GENRE_UPDATE_SUCCESS",
		FAILURE : "GENRE_UPDATE_FAILURE"

	},
	Delete: {
		REQUEST : "GENRE_DELETE_REQUEST",
		SUCCESS : "GENRE_DELETE_SUCCESS",
		FAILURE : "GENRE_DELETE_FAILURE"
	},
	Restore: {
		REQUEST : "GENRE_RESTORE_REQUEST",
		SUCCESS : "GENRE_RESTORE_SUCCESS",
		FAILURE : "GENRE_RESTORE_FAILURE"
	},
	Search: {
		REQUEST : "GENRE_SEARCH_REQUEST",
		SUCCESS : "GENRE_SEARCH_SUCCESS",
		FAILURE : "GENRE_SEARCH_FAILURE"
	},

	Clear: "GENRE_CLEAR"
}
