export const authorConstants = {
	Create: {
		REQUEST : "AUTHOR_CREATE_REQUEST",
		SUCCESS : "AUTHOR_CREATE_SUCCESS",
		FAILURE : "AUTHOR_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "AUTHOR_GETPAGED_REQUEST",
		SUCCESS : "AUTHOR_GETPAGED_SUCCESS",
		FAILURE : "AUTHOR_GETPAGED_FAILURE"
	},
	Clear: "AUTHOR_CLEAR"
}
