export const authorConstants = {
	Create: {
		REQUEST : "AUTHOR_CREATE_REQUEST",
		SUCCESS : "AUTHOR_CREATE_SUCCESS",
		FAILURE : "AUTHOR_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "AUTHOR_GETPAGED_REQUEST",
		SUCCESS : "AUTHOR_GETPAGED_SUCCESS",
		FAILURE : "AUTHOR_GETPAGED_FAILURE"
	},
	Update: {
		REQUEST : "AUTHOR_UPDATE_REQUEST",
		SUCCESS : "AUTHOR_UPDATE_SUCCESS",
		FAILURE : "AUTHOR_UPDATE_FAILURE"

	},
	Delete: {
		REQUEST : "AUTHOR_DELETE_REQUEST",
		SUCCESS : "AUTHOR_DELETE_SUCCESS",
		FAILURE : "AUTHOR_DELETE_FAILURE"
	},
	Restore: {
		REQUEST : "AUTHOR_RESTORE_REQUEST",
		SUCCESS : "AUTHOR_RESTORE_SUCCESS",
		FAILURE : "AUTHOR_RESTORE_FAILURE"
	},
	GetAllPaged: {
		REQUEST : "AUTHOR_GETALLPAGED_REQUEST",
		SUCCESS : "AUTHOR_GETALLPAGED_SUCCESS",
		FAILURE : "AUTHOR_GETALLPAGED_FAILURE"
	},
	Search: {
		REQUEST : "AUTHOR_SEARCH_REQUEST",
		SUCCESS : "AUTHOR_SEARCH_SUCCESS",
		FAILURE : "AUTHOR_SEARCH_FAILURE"
	},
	Clear: "AUTHOR_CLEAR"
}
