export const publishingConstants = {
	Create: {
		REQUEST : "PUBLISHING_CREATE_REQUEST",
		SUCCESS : "PUBLISHING_CREATE_SUCCESS",
		FAILURE : "PUBLISHING_CREATE_FAILURE"
	},
	GetPages: {
		REQUEST : "PUBLISHING_GETPAGES_REQUEST",
		SUCCESS : "PUBLISHING_GETPAGES_SUCCESS",
		FAILURE : "PUBLISHING_GETPAGES_FAILURE"
	},
	Update: {
		REQUEST : "PUBLISHING_UPDATE_REQUEST",
		SUCCESS : "PUBLISHING_UPDATE_SUCCESS",
		FAILURE : "PUBLISHING_UPDATE_FAILURE"

	},
	Delete: {
		REQUEST : "PUBLISHING_DELETE_REQUEST",
		SUCCESS : "PUBLISHING_DELETE_SUCCESS",
		FAILURE : "PUBLISHING_DELETE_FAILURE"
	},
	Restore: {
		REQUEST : "PUBLISHING_RESTORE_REQUEST",
		SUCCESS : "PUBLISHING_RESTORE_SUCCESS",
		FAILURE : "PUBLISHING_RESTORE_FAILURE"
	},

	Clear: "PUBLISHING_CLEAR"
}