export const userBookReadConstants = {
	Create: {
		REQUEST : "USER_BOOK_READ_CREATE_REQUEST",
		SUCCESS : "USER_BOOK_READ_CREATE_SUCCESS",
		FAILURE : "USER_BOOK_READ_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "USER_BOOK_READ_GETPAGED_REQUEST",
		SUCCESS : "USER_BOOK_READ_GETPAGED_SUCCESS",
		FAILURE : "USER_BOOK_READ_GETPAGED_FAILURE"
	},
	Delete: {
		REQUEST : "USER_BOOK_READ_DELETE_REQUEST",
		SUCCESS : "USER_BOOK_READ_DELETE_SUCCESS",
		FAILURE : "USER_BOOK_READ_DELETE_FAILURE"
	},
	Clear: "USER_BOOK_READ_CLEAR"
}
