export const userBookWantToReadConstants = {
	Create: {
		REQUEST : "USER_BOOK_WANTTOREAD_CREATE_REQUEST",
		SUCCESS : "USER_BOOK_WANTTOREAD_CREATE_SUCCESS",
		FAILURE : "USER_BOOK_WANTTOREAD_CREATE_FAILURE"
	},
	GetPaged: {
		REQUEST : "USER_BOOK_WANTTOREAD_GETPAGED_REQUEST",
		SUCCESS : "USER_BOOK_WANTTOREAD_GETPAGED_SUCCESS",
		FAILURE : "USER_BOOK_WANTTOREAD_GETPAGED_FAILURE"
	},
	Delete: {
		REQUEST : "USER_BOOK_WANTTOREAD_DELETE_REQUEST",
		SUCCESS : "USER_BOOK_WANTTOREAD_DELETE_SUCCESS",
		FAILURE : "USER_BOOK_WANTTOREAD_DELETE_FAILURE"
	},
	Clear: "USER_BOOK_WANTTOREAD_CLEAR"
}
