export const bookConstants = {
	Create: {
		REQUEST : "BOOK_CREATE_REQUEST",
		SUCCESS : "BOOK_CREATE_SUCCESS",
		FAILURE : "BOOK_CREATE_FAILURE"
	},
	GetPages: {
		REQUEST : "BOOK_GETPAGES_REQUEST",
		SUCCESS : "BOOK_GETPAGES_SUCCESS",
		FAILURE : "BOOK_GETPAGES_FAILURE"
	},
	Update: {
		REQUEST : "BOOK_UPDATE_REQUEST",
		SUCCESS : "BOOK_UPDATE_SUCCESS",
		FAILURE : "BOOK_UPDATE_FAILURE"

	},
	Delete: {
		REQUEST : "BOOK_DELETE_REQUEST",
		SUCCESS : "BOOK_DELETE_SUCCESS",
		FAILURE : "BOOK_DELETE_FAILURE"
	},
	Restore: {
		REQUEST : "BOOK_RESTORE_REQUEST",
		SUCCESS : "BOOK_RESTORE_SUCCESS",
		FAILURE : "BOOK_RESTORE_FAILURE"
	},
	GetById: {
		REQUEST : "BOOK_GETBYID_REQUEST",
		SUCCESS : "BOOK_GETBYID_SUCCESS",
		FAILURE : "BOOK_GETBYID_FAILURE"
	},
	GetPagedForUsers: {
		REQUEST : "BOOK_GetPagedForUsers_REQUEST",
		SUCCESS : "BOOK_GetPagedForUsers_SUCCESS",
		FAILURE : "BOOK_GetPagedForUsers_FAILURE"
	},
	Clear: "BOOK_CLEAR"
}
